import Link from "next/link";
import "./globals.css";
import Footer from "./template/Footer";
import Header from "./template/Header";
import Image from "next/image";
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { Poppins } from 'next/font/google';

import theme from './theme';

export const metadata = {
  title: "Taghazout Surf & Yoga",
  description: "Generated by humans , for humans",
};




// Charger la police "Poppins"
const poppins = Poppins({
  weight: ['400', '600', '700'], // Choisissez les poids que vous souhaitez utiliser
  subsets: ['latin'], // Sous-ensembles de caractères
  display: 'swap', // Pour une meilleure performance
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} min-h-screen flex flex-col `}>
      <ThemeProvider theme={theme}>
      <CssBaseline />
        <Header />
        {children}
        <Footer />
        <Link href={''} style={{
          position: "fixed",
          bottom: "1rem",
          right: "1rem",
          zIndex: 1000,
        }}>
          <Image src="/whatsapp.svg" alt="whatsapp" width={50} height={50} />
        </Link>
        </ThemeProvider>
      </body>
    </html>
  );
}
