import Link from "next/link";
import "./globals.css";
import Footer from "./template/Footer";
import Header from "./template/Header";
import Image from "next/image";
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';

import theme from './theme';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col `}>
      <ThemeProvider theme={theme}>
      <CssBaseline />
        <Header />
        {children}
        <Footer />
        <Link href={''} style={{
          position: "fixed",
          bottom: "2rem",
          right: "2rem",
          zIndex: 1000,
        }}>
          <Image src="/whatsapp.svg" alt="whatsapp" width={60} height={60} />
        </Link>
        </ThemeProvider>
      </body>
    </html>
  );
}
